export const en =
{
    "langId": 1,
    "langName": "english",
    "capitalName": "English",
    "langLocale": "en-US",
    "langLocaleAbout": "en-US",
    "rtl": false,
    "font": "Roboto-Light",
    "titleFont": "Roboto-Regular",
    "app_name": "O2Fit",
    "app_name_toolbarTitle": "Fit",
    "app_name_toolbarSubTitle": "o2",
    "pageName_CoockingPersonal": "pageName_CoockingPersonal",
    "pageName_Edit_Ingrrdient_Food": "pageName_Edit_Ingrrdient_Food",
    "pageName_Fragment_Gol_Limb_Body": "pageName_Fragment_Gol_Limb_Body",
    "cm": "cm",
    "tryAgin": "Retry",
    "ohhhh": "Ohhh!!",
    "noInternet": "Check your device internet connection !",
    "go": "Skip",
    "yourFoodHabbiteation": "Choose your eating habit",
    "adi": "Normal",
    "giah": "Vegan",
    "kham": "Raw Vegan",
    "pakGiahKhar": "Vegetarian",
    "haveYouAllergy": "Are you allergic to certain foods? Write below",
    "wrightYourFood": "exp: Eggplant",
    "continuation": "Next",
    "selectYoutSex": "Which one? girl or boy",
    "chooseCountry": "Choose your country of residence",
    "perBtn": "Back",
    "setYourPhicicalInfo": "Your Info",
    "height": "Height",
    "weight": "Weight",
    "brithDate": "Age",
    "todeBadan": "body mass index",
    "BMI": "BMI",
    "idealÙ€weight": "ideal weight",
    "kg": "kg",
    "the_BMR": "basal metabolic rate",
    "the_BFM": "total body fat",
    "LM": "LM",
    "the_WATER": "total body water",
    "the_IBF": "ideal body fat",
    "rateActivityToDay": " your daily activity",
    "helperRateActivity": "need help? tap here",
    "bedRest": "Bed Rest",
    "bedRest_description": "Bed rest",
    "normalLife": "Moderate",
    "normalLife_description": "exercise 4-5 times/week (15-30 minutes of elevated heart rate activity)",
    "littleActivity": "Light",
    "littleActivity_description": ": Exercise 1-3 times/week (15-30 minutes of elevated heart rate activity)",
    "relativelyActivity": "Active",
    "relativelyActivity_description": "daily exercise or intense exercise 3-4 times/week (45-120 minutes of elevated heart rate activity)",
    "veryActivity": "Very Active",
    "veryActivity_description": "intense exercise 6-7 times/week  (45-120 minutes of elevated heart rate activity)",
    "moreActivity": "Extra Active",
    "moreActivity_description": "very intense exercise daily, or physical job (+2 hours of elevated heart rate activity)",
    "setGol": "Set Your Goal",
    "youMost_1": "You should get",
    "youMost_2": "calories a day",
    "myProposal_2": "Kilos to Get Fit",
    "weightStability": "Maintain weight",
    "weightGain": "Gain weight",
    "weightLoss": "Lose weight",
    "weightLossAll": "Total Weight Loss",
    "yourGolWeight": "Set Your Goal",
    "whatLoss": "Lost Weight",
    "whatGain": "Gained Weight",
    "name": "Name",
    "family": "Family Name",
    "nameAndFamily": "Name and Family Name",
    "email": "E-mail Address",
    "password": "Password",
    "confirmPassword": "Re-pssword",
    "riferCode": "Referral Code(optional)",
    "country": "Country of Residence",
    "city": "City",
    "confirmRules_1": "By pressing the continue button i agree to the ",
    "confirmRules_2": "terms and conditions",
    "confirmRules_3": "",
    "enterConfirmCode": "Enter the 5 digit code we sent you via email",
    "confirmCode": "Verify",
    "dontGetConfirmCode": "Didn't get the code?",
    "editMobile": "Edit Number",
    "sendAgan": "Resend Code",
    "oxigenSendConfirmCodeTo": "Oxygen sent the code to [] \nplease check inbox/junk/spam folder-\ncode expires in:",
    "calorieGoal": "Budget",
    "baghimande": "Remaining",
    "moreKnowledge": "Learn More",
    "numberOfStepTodey": "Enter your",
    "glassUsed": "Intake",
    "glassIs": "Remaining",
    "glass": "Glass",
    "TapForGetMorInformationAboutYourBody": "more info, Tap Here",
    "numberOfVisit": "Number of Visitations:",
    "advertise": "Advertise",
    "advertises": "Advertises",
    "offerOfitt": "O2Fit Suggest",
    "sport_actives": "Exercises",
    "foodPart": "Meal",
    "yourMobile": "According to your phone",
    "add": "Add",
    "sleepInfo": "Sleep Information",
    "breakfast": "Breakfast",
    "lunch": "Lunch",
    "dinner": "Dinner",
    "snack": "Snacks",
    "set": "Change",
    "loding_text": "This may take a few seconds...",
    "motevajeShodam": "OK",
    "noInsertAllergyFood": "You are not allergic to any foods. If you are!, make sure you set them correctly.",
    "setOneFoodHabbitation": "You have to choose one of the eating habits.",
    "typeSexName_man": "Man",
    "typeSexId_man": "1",
    "typeSexName_woman": "Woman",
    "typeSexId_woman": "2",
    "noSelectSex": "You have not set your gender yet!",
    "no": "No",
    "yes": "Yes",
    "editInfo": "Edit Email",
    "ifWantTapNextBotton": "How fit are you?",
    "yourAmrazClick": "For More Info Tap Here",
    "yourAmraz": "You are exposed to these diseases:",
    "moreInfoActivity": "What does daily activity mean?",
    "youMostGetCol_1": "You should get",
    "youMostGetCol_2": "Calories daily",
    "myOfferForYou_1": "You should",
    "myOfferForYou_2_1": "weight loss",
    "myOfferForYou_2_2": "weight gain",
    "myOfferForYou_2_3": "maintain your weight",
    "doNotWorryForEditInfo_1": "Don't Worry\n\nYou can change your goal whenever you want.",
    "back": "Back",
    "ignorAndContinuation": "Got It, Continue",
    "empityNameFild": "The \"Name\" Field Is Blank",
    "botton_menu_home": "Home",
    "botton_menu_calender": "Diary",
    "botton_menu_gol": "Goal",
    "botton_menu_profile": "Profile",
    "date": "Date",
    "modWaterGlass": "Remaining",
    "modWater": "Remaining",
    "drinkWaterOtherFood": "Other Foods",
    "drinkingWater": "water intake",
    "saveWaterTitlePage": "Track water",
    "reguestWaterBody": "Daily Goal",
    "reguestWaterBody_number": "10",
    "startSleepTime": "Sleep Time",
    "endSleepTime": "Waking Time",
    "timeOfSleep": "Sleep",
    "min": "Minutes",
    "hour": "Hours",
    "whatIsRateForSleep": "Sleep quality rate",
    "saveSleepTitle": "Sleep record",
    "infoSleepTitle": "Sleep",
    "sleepChartTab_month": "Monthly",
    "sleepChartTab_week": "Weekly",
    "chartSabatSlepp": "Sleep Chart",
    "averageSleepTime": "Sleep Duration Average",
    "averageSleepRate": "Sleep Quality Average",
    "averageUsedColory": "Burned Calorie Average",
    "averageSleeping": "Sleeping Hour Average",
    "completInfoForBidyTitle": "your body data incorrect",
    "sizeOfGardan": "Neck",
    "sizeOfGardanDescription": "Circumference Of The Neck",
    "sizeOfShane": "Shoulder",
    "sizeOfShaneDescription": "Length Of Shoulders",
    "sizeOfSine": "Chest",
    "sizeOfSineDescription": "Circumference Of The Thickest Part Of The Chest",
    "sizeOfBazoo": "Arm",
    "sizeOfBazooDescription": "Circumference Of The Thickest Part Of The Arm",
    "sizeOfKamar": "Waist",
    "sizeOfKamarDescription": "Circumference Of The Thinnest Part Of The Waist",
    "sizeOfShekam": "High Hip",
    "sizeOfShekamDescription": "About 5 cm Lower Than The Waist",
    "sizeOfBasan": "Hip",
    "sizeOfBasanDescription": "Circumference Of Thickest Part Of The Hip",
    "sizeOfRan": "Thigh",
    "sizeOfRanDescription": "Circumference Of The Thickest Part Of The Thigh",
    "sizeOfMoche": "Wrist",
    "sizeOfMocheDescription": "Circumference Of The Thickest Part Of The Wrist",
    "shapeBodyInfoTitle": "Your Body information",
    "shapeBodyType": "Body Type",
    "shapeBodyInfo": "Body Shape",
    "shapeBodySport": "Best exercise for your body",
    "shapeBodyFood": "Nutrition for your body",
    "shapeBodyBad": "More Probable Diseases",
    "yourWeightOver": "[] kg Overweight",
    "yourWeightLow": "[] kg Underweight",
    "yourWeightNormal": "Normal Weight",
    "golWeight": "Weight goal",
    "currentWeight": "Current",
    "idealـweight": "ideal weight",
    "newWeight": "Current Weight",
    "setWeightTitle": "Record Weight",
    "setStepTitle": "Pedometer",
    "startWeight": "Starting Weight",
    "changeWeight": "Changed",
    "goTopLevel": "Go To Premium",
    "myProfile": "My Profile",
    "gol": "Goal",
    "shareForFriends": "Invite Friends",
    "invite": "Invite",
    "iConfirmCode": "Confirm",
    "invatedCodeFriend": "Invitation Code Entry",
    "allergyFood": "Food Allergy",
    "startWeek": "Calendar Week Starting",
    "notificationRemaind": "Reminder",
    "pm": "Messages",
    "security": "Password",
    "support": "Support",
    "report": "Report",
    "privacy": "Privacy",
    "guide": "Help",
    "oxygenFitt": "O2Fit",
    "exitApp": "Logout",
    "profileTitle": "Profile",
    "youDoUpLevel": "You can upgrade to Premium and unlock all features",
    "downAdv": "And Say Goodbye To Ads",
    "buyAccountTitle": "User Level Upgrade",
    "simple": "Simple",
    "gold": "Premium",
    "changeGol": "Update Goal",
    "textInexpensiveDoFitt_1": "Get",
    "textInexpensiveDoFitt_2": "In Shape",
    "textInexpensiveDoFitt_3": "By The Cheapest And Easiest Way Possible",
    "chooseByYou": "Your Call After All",
    "editGolTitle": "Update Goal",
    "golFittBoy": "Body info",
    "golInWeek": "Weekly Goal",
    "rateActivity": "burned",
    "rateActivity2": "Activity rate",
    "golCostFood": "Nutritional Goal",
    "InviteFriendsTitle": "Invite your friend,earn premium",
    "SubmitInviteFriendsTitle": "Enter Invitation Code",
    "InviteFriendsText": "By pressing share button you can send your invitation code and if 3 people sign up with the code, you will get a free month of premium.\n A 10% discount code will be applied to their first purchase as well.",
    "saved": "Save",
    "allergyFoodTitle": "Food Allergy",
    "PmTitle": "Messages",
    "securityTitle": "Password",
    "changePassword": "Change Password",
    "pasword": "Password",
    "confirmPass": "Re-type Password",
    "supportTitle": "Support",
    "supportDescription": "In case of any technical issues or bugs in the UI, you can easily report here and we will fix it as soon as possible.  Even if there is no problems, we will be more than happy to hear anything you have to say about the app.",
    "selectDepartment": "To",
    "writhYourTextForSupport": "Message",
    "notificationRemaindTitle": "Reminder",
    "pms": "Messages",
    "addWeight": "Record weight",
    "addNote": "Add Note",
    "notes": "Note",
    "notesTitle": "Notes",
    "addWaterUsedInDay": "Enter Daily Water Consumption Info",
    "addSleepingInDay": "Enter Daily Sleep Info",
    "notificationname": "Reminder Name",
    "timeRemaind": "Time",
    "iAte": "Save",
    "whatTimeAndHowMany": "How much?",
    "consumptionSize": "Amount",
    "meal": "Meal",
    "dateCedar": "Serving Date",
    "nutritionalValue": "Nutritions",
    "fat": "Fat",
    "carbohydrate": "Carbs",
    "protein": "Protein",
    "saturatedFats": "Saturated Fat",
    "unsaturatedFats": "Unsaturated Fat",
    "cholesterol": "Cholesterol",
    "sodium": "Sodium",
    "fiber": "Fiber",
    "sugar": "Sugar",
    "calcium": "Calcium",
    "moreView": "See More",
    "ingredient": "Recipe Details",
    "calories": "Calories",
    "tamam": "Done",
    "editFoodTitle": "Customize",
    "searchItemFoodTitle": "Search foods exp:egg",
    "searchItemFoodTitle2": "Search foods",
    "writeItemFoodSerch": "Enter ingredient name exp:red beans",
    "writeItemForSerch": "Enter food name exp: pizza",
    "lastFindBySearch": "The last things you searched",
    "addItemIngredientFoodTitle": "Adding Food",
    "whatIsAdd": "How much do yo want to Add?",
    "coockingPersonalTitle": "Recipe",
    "addPhoto": "Update Photo",
    "typeCoocking": "Cooking type",
    "timeCoocking": "Cooking time",
    "writeYourFood": "Enter food name here",
    "myCoocking": "Recipes",
    "restaurant": "Restaurant",
    "market": "Supermarket",
    "myFavorit": "My Favorite",
    "searchResult": "Food Search",
    "esyCoocking": "Quick and Easy",
    "coocking": "Add recipe",
    "addItemForYourFood": "Bake your foods by adding each ingredient and use its calorie and nutritional value in diary.",
    "isNotExistFavorite": "There is no favorite foods",
    "tapHeartToFavorite": "you only need to tap on the â¤ icon to get to quickly get your favorite foods",
    "foodAndItemFood": "Foods",
    "ifYouStartPedometer": "Tap button to start",
    "end": "Finish",
    "pedometering": "Auto mode",
    "setYourSteps": "how many steps per day would you like to reach?",
    "inTime": "Duration",
    "goFront": "You Went Forward",
    "get": "Left",
    "fire": "Exercises",
    "overFlow": "Over",
    "gr": "gr",
    "noFindItem": "No item found!",
    "noFindItemInNewSearch": "Sorry, no results found\nTry something else or create food.",
    "isSure": "Are you sure?",
    "tavajoh": "Attention!",
    "beforeChangPatternFoodVisitByDoctor": "If you are pregnant or have any health problems, you must consult with your Physician first before controlling your diet or counting your calories as it may be a risk to your health.",
    "golInDay": "Daily Nutrition Target",
    "micronutrientFood": "Micronutrient",
    "editGolNutritionalValueFood": "Edit Nutritions Goal",
    "limbBody": "Body",
    "EditLimbBody":"Measurement",
    "now": "Current",
    "change": "Change",
    "sizeMyLimb": "My Body Size",
    "saveSizeMyLimb": "Record body size",
    "editGolSizeMyLimb": "Organ goal",
    "golSizeLimbTitle": "Measurements",
    "golActivity": "Activity",
    "numberStepsInDay": "Daily steps",
    "editGolActivity": "Update Goal",
    "selectOneCountry": "Residence Country",
    "selectOneCity": "City",
    "tanks": "Thanks",
    "empityDoreSineFild": "The chest circumference field is blank.",
    "empityDoreBazooFild": "The arm circumference field is blank.",
    "empityDoreKamarFild": "The waist circumference field is blank.",
    "empityDoreShekamFild": "The abdominal circumference field is blank.",
    "empityDoreBasanFild": "The hip circumference field is blank.",
    "empityDoreRanFild": "The thigh circumference field is blank.",
    "fillAllFild": "Please fill all fields",
    "whatisTypeCooking": "How to cook this food?",
    "noInsertAmountUsed": "How much did you eat?",
    "noInsertNoteText": "Write a new note",
    "iBuy": "Buy Now",
    "sendCodeViaShare_": "If you want to keep track of your diet, install O2Fit. It is free to use and you can enter my invitation code to get 10% off of your first subscription to access the premium content.",
    "sendCodeViaShare_2": "Android Version\nhttps://play.google.com/store/apps/details?id=com.o2fitt\niOS Version\nhttps://apps.apple.com/us/app/o2fit-diet-calorie-counter/id1556681170\nO2Fit website\n\nhttps://o2fit.me/Products/DownloadApplication\n\nwww.o2fitt.com",
    "enterToApp": "Already signed up?",
    "noValidMin": "The minute value is not entered correctly",
    "noValidHours": "The hour value is not entered correctly",
    "forgetPassword": "Forgot my password",
    "insertYourMobileOrEmailForForgotPass": "Enter your email address ",
    "sendYourCode": "send code",
    "mobileOrEmail": "Email address ",
    "ya": "Or",
    "loginToFiit": "Sign In",
    "iRegister": "Sign Up",
    "setChangePassword": "Update Password",
    "subject": "Title",
    "selectSubject": "Choose a title",
    "noText": "No texts are typed yet",
    "notFindBarCode": "The product code is unreadable on the barcode",
    "matalebeMofid": "Articles",
    "fileIsMadeDownload": "The report is ready for download as a pdf file.\n    \\n\\n\n        You download?",
    "modeColories": "Remaining",
    "getColories": "Intake Calorie",
    "selectOneOption": "Please select an item",
    "IamSelect": "I choose",
    "measure": "Unit Of Measurement",
    "selectOneMeasure": "Select a unit of measure",
    "editPhoto": "Update Photo",
    "phone": "Phone",
    "gender": "Gender",
    "dailyActivity": "Daily Activity",
    "foodHabbiteation": "Eating Habits",
    "lastWeight": "Recent",
    "isNotExistFavoriteSport": "Still you have no favorite sports!",
    "isNotDefindeSport": "Or you haven`t recorded any exercise or activity yet",
    "writhYourResturant": "Enter restaurant name exp: KFC",
    "writeItemForSerchShop": "Food name for exp: Magnum Ice Cream",
    "measureForIdGlass_inSearch": "Glass",
    "golStep": "Steps target",
    "golStepDescription": "Set goal for steps in a day",
    "setStepToday": "Today Steps",
    "writeItemForSerchSport": "Exercise name exp: Badminton",
    "second": "Second(s)",
    "usedCalories": "Burned Calorie",
    "addSportTitle": "Add Exercise or Activity",
    "countCalories": "Add Calories",
    "selectYourTypeReport": "Choose the type of your report to send you to the file",
    "selected": "Choose",
    "reportsTitle": "Reports",
    "sendToMy": "Send Me",
    "addWater": "Water",
    "noInsertUserName": "You have not entered the username",
    "fromPage_ForgetPassword": "ForgetPassword",
    "selectTypeCalender": "Select the calendar type of the application",
    "selectTypeCalender_en": "Choose calender type",
    "calender_shamsi": "Persian Calendar",
    "calender_miladi": "AD Calendar",
    "dateStartSleep": "Sleep Time",
    "durationStartSleep": "Duration of Sleeping",
    "getWaterOtherFood": "From Foods",
    "yourSleepChart": "Would you like to see more information about your sleep?",
    "coloriesDaily": "Calorie Bar",
    "burnColories": "Calories Burned",
    "cancel": "Cancel",
    "insertTimeStart": "Enter the Time of Starting your Walk",
    "startYourSteps": "Walk Starting Time:",
    "insertStartTimeStep": "Enter the starting time of the walk correctly!",
    "MuscleGol": "Target Muscle",
    "MuscleInvolved": "Involved Muscle",
    "homeFavorite": "Cardio",
    "bodyBuldingFavorite": "Bodybuilding",
    "exerciseFavorite": "Exercises",
    "addNewSport": "New Exercise",
    "addNewSportTitle": "Add New Activity",
    "writeNameSport": "Exercise name",
    "coloriesNumber": "Calories",
    "colories": "Calories",
    "fillFildeSport": "You have to fill these fields if you burn 70 calories for a 30 minute local dance.    \\n\\n\n        Local Dance\n        \\n\\n\n        70\n        \\n\\n\n        00:30",
    "countChange": "Weekly Goal",
    "verifyCode": "Verification Code",
    "newPassword": "New Password",
    "send": "Send",
    "male": "male",
    "female": "female",
    "idealYourWeight": "Your Ideal Weight",
    "paymentText": `Oxygen Fit Premium\nTo provide most effective and most personalized program for losing or gaining weight and fitness of your body, we have added some new features in addition to calorie counting and pedometer. \nIn the following, we are providing you their explanations.\n\nManagement of nutritional value\nConsume foods based on your conditions\n\n You can determine 34 target nutrients and after eating any foods or meal, it control and\n displayed absorbed nutrients automatically, which is so good for you. \n \n Daily water\nDrink water based on your need\n\nThe amount of needed water for any person can vary among different people because of their physical conditions. We determine the needed amount of water using data obtained from your body and then control it.\n\nAbsorbed waster from foods\nYou should know that how much water you absorb from any food It can be very interesting to know that how much water you absorb after eating any foods! We do this automatically and control it and you can view the result in "water" section.You only have to list how much foods or beverages you have consumed that day.\n\nBody information\nKnow your body\nIn Oxygen Fit, you can see your body's information like body type, body figure, body mass index (BMI), ideal weight and many more by entering your sizes. You can also see which diseases are threatening you. We help you to control the health level of your body.\n\nExercises and sports\nLet us exercise a bit more\n\nExercising is one of the best methods for body fitness and improving your health. Oxygen Fit can help you to have more exercises and movement; because it can offer you 800 different types of exercises and activities, 118 home-based exercises and 1000 strength exercises or body-building along films and full information and calculation of consumed calories compared to your weight.\n\nSleep control \nDid you sleep well today? \n\n With Oxygen Fit, you can register the amount of daily sleep and its quality and have access to your weekly or monthly sleep information.\n\nGoal\nDecide and do it\n\nYou can determine your desirable goal for your body and revise it as necessary in the path of success.\n\n Viewing charts and reports\nRight at the path of success\n\nYou can have reports for anything for any periods, including burnt calories, nutrient absorption, and body size and more. \n\nPersonalized food-maker\nCustomize all foods\n \n You can have reports for anything for any periods, including burnt calories, nutrient absorption, and body size andâ€¦\nOne unique and interesting of Oxygen Fit is called personalized food-maker. \nYou can define your food, add things to it and even attach its pictures and its recipe to it. \nThen, you say how much you have eaten and then you can see how much your body has absorbed in terms of calorie, water and nutrients.\n\n Without ads. \nNo ads will be displayed on this app if you have a premium.`,
    "noFindItemFood": "The food barcode was not found in database!",
    "shapeBodyHarmfulFood": "Harmful Foods to You",
    "shapeBodyOverweightInParts": "Fat Reserve",
    "pakagNameSelected": "Your Selected",
    "finalPay": "Final Payment",
    "byEditItemsAddNewFood": "You are creating a new food by editing the ingredients of this food, so the name of the new food is required.\n\nDo you want to continue?",
    "kgMeasureName": "Kg",
    "the_FM": "Body Fat Mass",
    "the_LM": "Lean Body Mass",
    "the_over": "Rate of Overweight/Underweight",
    "the_maximumWeight": "Max Weight",
    "the_minimumWeight": "Min Weight",
    "selectPackage": "Select one of the packages.",
    "SelectBankTitle": "Invoice",
    "priceUnitEuor": "Euro",
    "amount": "Amount",
    "discount": "Discount",
    "payable": "Due Amount",
    "discountCode": "Discount Code",
    "applyCode": "Apply Code",
    "viewDiscountList": "Discounts list",
    "noDiscountList": "No available discounts",
    "tabrik": "Congratulations!",
    "isSuccessFullBuyPakage": "Payment was successful",
    "startTime": "Starting Time",
    "noValidInsertDurationTime": "The activity duration is not entered correctly.",
    "changeTargetNutritionTitle": "Edit Nutrients goal",
    "golDailyNutritionFood": "Nutritions",
    "valueText": "Value",
    "isEmpity": "is blank",
    "caloriesCalculat": "Calculate",
    "insertWristSize": "Enter the size of your wrist circumference so we can tell you your daily calorie intake better",
    "errorNoInsertWrist": "You did not enter your wrist size. If you have disability in this part, enter the value 0.",
    "errorKgWeight": "You have only entered the gram value in New Weight section and the kilo value is not entered",
    "noInsertGolStep": "You didn`t enter the target of your steps number!",
    "used": "Absorbed",
    "insertNewPass": "Enter your new password",
    "year": "Years Old",
    "tanksToBuy": "Thanks for your purchase",
    "isBuyPackageNow": "Unfortunately, you are not currently able to access this section, because you do not have an O2Fit subscription.\n    \\n\\n\n        Do you want to buy subscriptions now?",
    "isBuyPackageNowForResult": "Unfortunately, you can have access to a limited number of results for now, because you do not have an O2Fit subscription.\n    \\n\\n\n        Do you want to buy subscriptions now?",
    "buyPackage": "buyPackage",
    "isDeleteRow": "Do you want to delete?",
    "mobile": "Mobile number",
    "address": "Address",
    "ZipCode": "ZipCode",
    "descriptionBank": "note",
    "myWorkoutPersonal": "My Exercises",
    "noExistFavoritSport": "You did not select any exercise as an favorite",
    "editHowMany": "Edit Consumption Amount",
    "areYouWantChangTargetWeight": "Are you sure you want to change your target?",
    "insertTargetStep": "Daily step goal",
    "the_dailyCalories": "Basal Metabolic Rate",
    "empityAllFilds": "All fields are blank.",
    "addSportHomeTitle": "Add Cardio Exercise",
    "addSportBodyBildingeTitle": "Add Bodybuilding",
    "addSportExriesTitle": "Add Exercise",
    "addIngerdientFood": "Add Food",
    "lastPassword": "old Password",
    "dataEntryEN": "Fill the field in English",
    "fillEN": "Fill all the fields in English",
    "viewBodyShape": "Measurements",
    "yourAccountToDate": "days left to premium",
    "step": "Step",
    "editStepTitle": "Step Update",
    "checkYourSpam": "The activation code was sent to your email, please check the inbox, spam or junk folder.",
    "selectMeasur": "Measure Unit",
    "addNameItemFood": "Add ingredients to food",
    "reTry": "Retry",
    "unSuccessPaymentBanck": "Payment Unsuccessful",
    "gotoHomePage": "Go To Home",
    "ERROR_TYPE": "ERROR_TYPE",
    "donotCamera": "The Camera Is Not Active On Your Device!",
    "yourInfoBodyIsNotCompelet": "Due to incomplete measurements of your limbs, your body shape and information may not be displayed correctly.\n\nAre you completing your information now?",
    "value": "Amount",
    "areShureExit": "Do you want to exit app?",
    "register": "Sign Up",
    "privateText": "The intimation of policy and privacy protection\n\nIntimation of O2fit policy and privacy informs users about their responsibilities and makes them aware of selecting a behavior so that their personal information is not been abused.\n\\n\nThis secrecy policy is complied and executed by Oxygen holding, the owner of Oxygen software.\n\\n\nThese policies may periodically amend or change. If there are made alternations based on collecting procedure, using, and or data transition, we make you aware of the reformed version of the secrecy policy through E-mail. If you use the O2fit system after 4 days, it will be considered as awareness and acceptance of all the provisions. If O2fit starts to collect the information except for the mentioned cases in this intimation, it is obligatory to have your consent.\n\\n\\n\nThis intimation refers to the following cases:\n\\n\n1.A personal information set\n\\n\nO2fit collects and uses your information for utilizing and increasing your experience in websites and the other programs of Oxygen.\n\\n\nO2fit will never share your information with others. If O2fit use them to develop its own business, it should present a behavior so that the users are not known.\n\\n\nUsersâ€™ information\n\\n\nFurthermore the information of an individual that is required to develop a user account, we also collect O2fit standard information, such as:\n\\n\na) The information related to a personal diet as birth, height and weight, genes, and the special details of foods and drinks that you use and the exercises you do and your sent tests results.\n\\n\nb) Email address and password\n\\n\nc) Your IP address, browser type and, working operating system.\n\\n\nd)  Visited and referred pages, websites, and visits dates and time.\n\\n\ne) Financial information, for example, credit card number, the bill information of purchases and product promotion\n\\n\nf) Geographical situation data and the other information about organizations that are used for accessing and interacting with websites or programs.\n\\n\ng) You make data available using the tools that exist on websites or through a program or send them publicly.\n\\n\n\\n\nh) You may give the information to a user in a userâ€™s messages.\n\\n\ni) The collected information from ads and third party firms.\n\\n\nj) The information shared by tutors, and physicians. Also the information such as name, the firmâ€™s name and the pictures they have presented.\n\\n\nk) Supplementary information: your information may be completed with the additional information of the other resources, such as the available public resources.\n\\n\\n\n2. Using the personal information\n\\n\nWe will treat confidentially with the collected information, and we do not share your identification of personal information without your assenting.\n\\n\nWe may:\n\\n\n-Share the information that does not potentially cause your identification, like the average of usersâ€™ weight reduction and or general information about eating habits, diets, and exercises. And this information develops based on collected statics from data, and or data that does not determine as a special user.\n\\n\n- For proving the services and products that you request us.\n\\n\n- Whereas cooperating in challenges, competence, and opinion polls of O2fit, we may fulfill the advertisement with the other cooperated supporters.\n\\n\n- To share the usersâ€™ unidentifiable information in events and market analysis for the commercial objectives for marketing or improving the services.\n\\n\n- If, based on a legal judgment, O2fit is to be liable to give personal information to cognizable authorities.\n\\n\nUsersâ€™ information is considered as a part of the Oxygen holding assets. So if there is done a commercial transaction, like integration with another firm, or purchasing a part of the Oxygen holding asset the considered organization is obliged to treat with usersâ€™ personal information, diets, and such information, according to the secrecy policy.\n\\n\nIn some situations, we may take action through third party contractors to perform the services. In this way, they will be provided only with the necessary information to render the services (e.g. in the case of recovering a physical product to you by a contractor, your name and address are presented o the contractor) and all contractors are asked to endeavor in retaining the personal information.\n\\n\nDespite all the above issues, usersâ€™ collected data, except ads in importing health to prove safety and health, and or the other Oxygen team software will not be used.\n\\n\\n\n3. Sharing the information with friends, tutors and physicians\n\\n\nO2fit provides this possibility for you to share diets and exercise plans, aims, and other information with friends, tutors, and physicians. If you confirm using a club and physician, receiving their services requires giving your personal information to them, and by making this part, you accept that they access your information.\n\\n\nPlease, consider that O2fit cannot control your shared information, therefore, please share your information with reliable friends, tutors and physicians.\n\\n\\n\n4. Collected information security\n\\n\nWe have done commercial-security measures to protect your information against security violations. For instance, we store the personal dietary information in a limited and safe accessible possibility. And we take advantage of standard firewalls and security software which have designed to protect the security and the information integrity. However, there is no guarantee for accessing information, revelation, alteration, or destruction of information. Using O2fit and programs and websites and its services, you confirm the achieving the perception of these dangers and if each of the above cases occurs, we do not accuse the Oxygen group.\n\\n\\n\n5. Supporting children privacy\n\\n\nO2fit is a popular site and we do not intend to serve the children. If you are less than 18 years old, you are not allowed to use a website, and or software of O2fit (see the public regulations of data protection (COPPA). The Oxygen holding will block such individualsâ€™ accounts.\n\\n\\n\n6. Using cookies and tracking technology\n\\n\nThe cookies have short textual files that place on a userâ€™s hardware hard disc and make the access of primary information more simply as some regulations in reentering to a website, avoiding re-registration in any entrance to the website.\n\\n\nWe use cookies to obtain internet usage knowledge improving content and advertisement, collecting visited sites data and in some cases, they are used to present the professional issues.\n\\n\nSome of our advertisers and business partners sometimes use it. O2fit has no monitoring of used cookies by its advertisers and business partners.\n\\n\nIf you donâ€™t want to use the cookies, you can achieve this wish by inactivating them on your browser. It is necessary to note that in this way, a part of the website may not act correctly.\n\\n\\n\n7. Connecting with the other websites\n\\n\nOur website may connect with other websites. Note that we arenâ€™t responsible for other websâ€™ and firmsâ€™ procedures for privacy protection. So we encourage you to investigate the other websitesâ€™ privacy protection policies that you connect to them in this way. The third partiesâ€™ proceedings and policies are not under our control.\n\\n\\n\n8. Legal and civil bases\n\\n\nFor data processing, we will proceed based on the following bases:\n\\n\nContrast revenue: if you begin to promote the program through the website, you must assist the necessities of O2fitâ€™s intended individualsâ€™ particulars presentation so that your request is agreed upon.\n\\n\nSatisfaction: we are allowed by ourselves using some of your given personal information that has mentioned in this intimation of privacy protection policy, and we make you pleased.\n\\n\nLegitimate advantage: Using your personal information to improve the products and services for commercial or health aims and the other Oxygen team software that would have done along with this policy are a part of our legitimate advantages has been proven by your satisfaction.\n\\n\nData processing: Usersâ€™ data processing toward their geographic condition and, based on local limitations, traffic and so on, will be performed according to the technical groupâ€™s decision making of the Oxygen group, regarding Oxygen teamâ€™s defined algorithms.\n\\n\\n\n9. Data preservation and information omission\n\\n\nWe will retain your personal information only until achieving the aims to which they have been gathered and processed, such as legitimate, regulatory, audit, and declarative accountability.\n\\n\nOur policy is to retain your personal information for six months after your user account omission or disuse. It is necessary to note that the Oxygen holding secures the right of using usersâ€™ personal information along with this policy intimation for more than six months for itself.\n\\n\nWhile say welcome to you, if there are any questions or suggestions, you can contact info@o2Fitt.com.\n\\n\nOxygen Team\n\\n\nLast update, On 21 Jan. 2021",
    "serverError": "Server connection error\ncheck internet connection",
    "userNameOrPassIncorrect": "Wrong username or password",
    "duplicateUserName": "This username has already been taken",
    "DangerousThinness": "Severe Thinness",
    "worryingThinness": "Moderate Thinness",
    "thinPerson": "Thin",
    "normalProportionalStatus": "Normal",
    "havingOverweight": "Overweight",
    "havingVeryOverweight": "Obese Class I",
    "worryingOverweight": "Obese Class II",
    "dangerouslyOverweight": "Obese Class III",
    "week": "week",
    "sports": "Exercises",
    "aerobic": "Cardio",
    "myWorkouts": "My exercises",
    "dateError1": "Time is wrong",
    "dateError2": "Waking time should not be before bedtime",
    "sh": "Sat",
    "1sh": "Sun",
    "2sh": "Mon",
    "3sh": "Tue",
    "4sh": "Wed",
    "5sh": "Thu",
    "jome2": "Fri",
    "successful": "Saved successfully",
    "ok": "Ok",
    "ectomorph": "Ectomorph",
    "endomorph": "Endomorph",
    "mesomorph": "Mesomorph",
    "hourGlass": "Hour Glass",
    "topHourGlass": "Top HourGlass",
    "apple": "Apple",
    "pear": "Pear",
    "triangle": "Triangle",
    "invertedTriangle": "Inverted Triangle",
    "rectangle": "Rectangle",
    "unknown": "unknown",
    "hgdf": "Raw vegetables and fruits,Whole grains,Beef,Low fat yogurt,Seaweed",
    "hghf": "Caffeinated beverages,Refined carbohydrates,Water contains fluoride and chlorine, Types of cabbage, Soy, peanuts",
    "hgsd": "Thyroid",
    "hgss": "walking, jogging, swimming, treadmill, elliptical trainer.",
    "apdf": "Raw vegetables and fruits,Whole grains,Beef,Low fat yogurt,Seaweed",
    "aphf": "Caffeinated beverages,Refined carbohydrates,High sugar fruits,High-fat and ready meals",
    "apsd": "Diabetes, stroke,IBS and digestive problems,Constipation and water retention in the body",
    "apss": "Aerobic, HIIT,Walking, jogging, Jumping rope, Zumba,Swimming",
    "thgdf": "Complex carbohydrates, low-fat dairy, fresh vegetables and fruits",
    "thghf": "Coconut oil, cheese, butter, canola oil, vegetable oils and seed oils, heavy meats, salty snacks, caffeinated beverages",
    "thgsd": "Heart and joint inflammation",
    "thgss": "walking, jogging, swimming, treadmill, elliptical trainer.",
    "pedf": "Fiber-rich vegetables and fruits, small amounts of animal protein, non-dairy fats such as coconut oil, flaxseed, legumes and eggs",
    "pehf": "High-fat cheeses, cream, sauces, caffeine and alcohol, processed meats such as sausages, etc.",
    "pesd": "Diseases related to estrogen levels such as progesterone, inflammation of the joints, especially the thighs as cellulite, water retention, bloating",
    "pess": "running , step aerobics, dancing, Zumba, elliptical trainer",
    "trdf": "Fiber-rich vegetables and fruits, small amounts of animal protein, non-dairy fats such as coconut oil, flaxseed, legumes and eggs",
    "trhf": "High-fat cheeses, cream, sauces, caffeine and alcohol, processed meats such as sausages, etc.",
    "trsd": "Diseases related to estrogen levels such as progesterone, inflammation of the joints, especially the thighs as cellulite, water retention, bloating",
    "trss": "running , step aerobics, dancing, Zumba, elliptical trainer",
    "rtrdf": "Complex carbohydrates, low-fat dairy, fresh vegetables and fruits",
    "rtrhf": "Coconut oil, cheese, butter, canola oil, vegetable oils and seed oils, heavy meats, salty snacks, caffeinated beverages",
    "rtrsd": "Heart disease",
    "rtrss": "Push-ups , Bench presses , Abdominal crunches, Reverse crunches",
    "rcdf": "Balanced foods with carbohydrates, fats, proteins and fiber",
    "rchf": "Protein powder, shake, large chunks of meat",
    "rcsd": " vitamin deficiency",
    "rcss": "Planks, Push-ups , Pull-ups , walking , jogging , dance",
    "subscribe1": "Upgrade to unlock",
    "reminder1": "it's time to update breakfast calories!",
    "reminder2": "it's time to update lunch calories!",
    "reminder3": "it's time to update dinner calories!",
    "bigNutrition": "Macronutrient",
    "camera": "Camera",
    "gallery": "Photos",
    "choose": "Choose",
    "foodNoValue": "Due to the long cooking time,has lost its nutritional value.",
    "paymentReceipt": "Payment Receipt",
    "updatingDatabase": "Updating Offline Data",
    "onlineSearch": "Loading online results",
    "invalidReferreral": "Referral code is Invalid ",
    "welcomeonboarding": "We will guide you through your journey of getting healthier.\nThere are various options in Oxygen Fit which can help your progress and allow you to reach your goal faster.",
    "calorieonboarding": "You can input anything you ate today, create your own food by using the 3000 ingredients we support or simply enter your favorite meal from your favorite restaurant.\nNutrition facts for ingredients and food will be presented as well.",
    "exerciseonboarding": "You are provided with more than 1000 different exercises including calisthenics and weightlifting, and over 200 sports categories which can all help you keep track of your daily activity and how much calories you are burning.",
    "foodmakeronboarding": "We have pioneered a facility which helps you cook your meal from among the ingredients provided in this application, and see its calories and food facts.",
    "goalonboarding": "You can apply or edit 27 different programs. Besides, together with every program, you can take advantage of the precise details we provide you with according to your body shape",
    "nutritionalValue100": "Nutrition per 100g",
    "sendMsg": "Send",
    "invalidMail": "Invalid email address",
    "confirmRules": "Please accept terms and condition",
    "pedTitle": "Select one of the pedometer modes below",
    "onboardingTitle1": "Welcome to O2Fit",
    "onboardingTitle2": "Smart Calorie Counter",
    "onboardingTitle3": "Keeping Track of Your Workout",
    "onboardingTitle4": "A Customized Food",
    "onboardingTitle5": "Goal and Food Diary",
    "terms": 'Terms of Service\nThe following set includes conditions which have been legislated by Oxygen Group in relation to O2Fit software and all website services, website address, mobile apps and all other websites which are trading and serving you as a user or a beneficiary of this service by this company and offered to you by managers, staff, agents and each of dependent institutions to Oxygen Group. \n\nYou confirm that you have studied and agreed all the provisions of these conditions by representing your mobile phone number or email address or by creating a user account and you will consider and execute all determined limits in this code and Oxygen Group will save the right to change or revise it at any time and in any place and only through announcing you for once. \n\nHereby, it includes all users such as those who use it exclusively for their own personal diet and also those users who use it as physician or coach (those who guide a group). \n Please read the conditions of this letter of agreement carefully and refer to this part periodically to be aware of any changes. \nIn the case that you donâ€™t accept these conditions, please donâ€™t use this service. \n\nArticle 1- Registration\nIf you register, you have attested that 1) you have come of making contract age 2) your information is registered completely, accurately and update 3) your registration and using Oxygen services have not been banned by law. \nHowever, Oxygen Group has right to limit, suspend or block your registration or access to O2fit services in the case of violating each of conditions, announcing you or not. \n\n Article 2- Children\nThe services of Oxygen Group in relation to all soft-wares of O2fit (including website and mobile apps) are not for the use of individuals younger than 18. If you are younger than 18 years old, you are not allowed to register as a user or in any other way. \n\nArticle 3- Commercial Intellectual Property Rights of Oxygen Fit (O2fit) \nAll contents, writings, logos, compilations (collecting, regulating, ordering, arranging and assembling information) or any other content, software and existing shows on website and O2fit app or used by O2fit except the contents represented by the users are exclusively for Nations Oxygen Data Processing Company (privately held company) and the official commercial partners of this company. \nOxygen Group has reserved explicitly all rights appointed to itself such as intellectual property rights about all above mentioned items, except those which have been mentioned among these conditions explicitly and bans any use, redistribution, replacement, reverse engineering, parts separation, translation or other kinds of exploiting them. \nO2fit is a registered commercial mark which belongs to Nations Oxygen Data Processing Company (privately held company) and it canâ€™t be used by any other person or company in relation to any type of services or products which may confuse customers or invalidate Oxygen Group. Any kind of using these marks or other items which are shown in this service are exclusively in the interest of Nations Oxygen Data Processing Company (privately held company). \n \n Article 4- The Content of Usersâ€™ Registration\nInformation like name, personal image, telephone number, email address and password are regarded as your personal information and O2fit is responsible to protect them and not transfer them to any other person or company. Other information that you send as a part of your registration including any data, photo (except personal image), text, graphic, movie and other contents you send O2fit is among your shared information and Oxygen Group is able to use them to improve the quality of website or app. The user is not allowed to demand for publication right or another intellectual property about representing such information. So you agree that Oxygen Group is allowed to register all your information, protect them and use them as a new content after monitoring them. The mentioned right is exclusive, universal, transferable, permanent and unreturnable to publication, distribution and representation and the represented content of the user in relation to these services or other services belong to Nations Oxygen Data Processing Company (privately held company) is exploitable. \n \n Article 5- Using Services License\nO2fit allows you to use the services of this website and app considering the provisions of this letter of agreement for non-commercial and personal purposes. O2fit services divided into two free and shared parts and it is possible to use shared services when the user has paid for it. The content of above mentioned services and their prices are on website and app and you are not allowed to change them. By paying the cost related to using shared services, you can use permitted services mentioned on website and app but this doesnâ€™t permit you to copy, publish, distribute, reverse engineering andâ€¦which are mentioned above. O2fit website and app wonâ€™t be sold and the users donâ€™t have right to copy this software related to service except the mentioned rights in this article and they wonâ€™t obtain any other right by payment. \nTherefore, you agree and guarantee that your use of O2fit website and app services is consistent with aforementioned items and limitations and you wonâ€™t violate the opposite partyâ€™s right and you will adhere to your responsibilities and duties and take the responsibility of your personal violations about not observing conditions related to O2fit. \nWe reserve the right to make any changes on website and app (including free or shared parts) at any time even without informing users for itself and you confirm that you are aware of this matter. \nYou agree that sometimes O2fit services may be out of reach for improving quality, technical problems or probable changes in special occasions (limited or unlimited). In the case of such situation, no responsibility (unlimited) wonâ€™t be subjected to any of Oxygen Group members. \n \n 6- Payment\n6-1 Sum and Shared Services\nIf you purchase shared package, youâ€™ve paid taxes on it and O2fit wonâ€™t have another request to pay tax. These prices may differ at any time according to the policies of the target country. You will pay the considered sums to Nations Oxygen Data Processing Company consciously through the introduced bank gate and the dependent companies may save your payment characteristics based on their own policies. Payment is based on your subscription duration and the agreement of offering services will be cancelled automatically at the end of selected time. In the case that the interacting bank wonâ€™t adhere to its responsibilities (absolute and on time payment) and problems occur in your payment, Nations Oxygen Data Processing Company wonâ€™t be responsible for this matter. The users are not allowed to cancel the purchased services before the end of purchased period. \nAll differences in account between user and Nations Oxygen Data Processing Company (privately held company) have to be reported in 24 hours from the time of difference occurrence and Oxygen Company will soon take measure to respond. \n \n 6-2 Repayment Policy\n None of your payments will be returnable and you can use shared services of O2fit during the determined period and representing services to you will be terminated at the end of mentioned period. It is natural that in the case of reusing, the user is able to use mentioned services to extend the shared service. \n\nArticle 7- Non-Obligatory Items\nO2fit considers the following items as its rights obligatory: \nTo save userâ€™s information content. \na)To match userâ€™s registered content and information with the terms of services of the agreement letter and to decide based on this conformity. \nTo remove userâ€™s illegal or destructive contents or userâ€™s illegal registration information which are not consistent with the terms of services of this agreement letter. \nTo supervise, to edit and to show contents represented by user or generally supervise how to use this service. \nTo take measure to edit and or to remove usersâ€™ registration content or information except those users who violate the terms of services of this agreement letter. \n \n Article 8- The Source and the Volume of Represented Information to the Users\nThe represented information to the users in different parts has been prepared considering nationality, habits and other localizable parameters. For example, there are more than 500.000 foodstuffs in foodstuff part produced in factories with name, manufacturing company, brand name, weight, consuming gauges and the amount of micronutrients and macronutrients related to each stuff that the number of records related to foodstuffs reaches more than 55.000.000 practically. Manufacturing companies usually represented a limited number of nutritional values. The Oxygen Group aims at representing a full list of foodstuffs to help users take step in health with full information, so any disagreement among users has to be reported to O2fit to be modified and then confirmed. Oxygen Group appreciate your this measure. \n\nArticle 9- Linking with Third Partyâ€™s Websites\n O2fit website may have links to third partyâ€™s websites. The related websites are not under our control and we are not responsible for none of linked websites. We have only put these links on website and app for easiness and it doesnâ€™t mean any confirmation, financial support or dependency to the related website. Therefore, it is necessary to search about these third parties before making any deal with them. \n \n Article 10- Sent Ideas to O2fit \n O2fit welcomes your opinions and suggestions. If your sent suggestion be confirmed by us and be used on website and app, we wonâ€™t take any responsibility about the disclosure of received suggestion or its unlimited use and we are allowed to use it in any way, commercially or non-commercially, media and orâ€¦without paying compensation to the recommender or the creator or writer of that idea. \n\nArticle 11- Depriving Responsibility, Responsibility Limitation, Compensation\nYou confirm that your diet and sport activities may be dangerous they may cause damage or be life-threatening and you take the responsibilities of these dangers. \nYou have to consult with nutritionist and permissible and valid health cares before starting or changing your diet and sports and to confirm that O2fit has recommended you to so such consultations. \n Pregnant women mustnâ€™t use such services. O2fit services is merely an information source and doesnâ€™t offer medical consultation. Medical services servers have been predicated and defined according to the rules and regulations of each country. \n \n O2fit takes no responsibility for the use of services that you use in sports, foodstuffs and other services.',
    "confirmcodealert": "Incorrect Code",
    "wrongUserName": "Incorrect username",
    "birth": "Birth",
    "personalInfo": 'If you do not know the size of the wrist, you can measure it later.',
    "fillAllFild2": "The username or password is incorrect.Please check your username & password and try again.",
    "moreInfoActivity": "What does daily activity mean?",
    "details": "details",
    "noSubscribe": "Upgrade to unlock more features",
    "riferCode2": "Referral code",
    "ingList": "Food Details",
    "noValidInsertDurationTime2": "Select cooking time",
    "noValidCookType": "Choose cooking type",
    "reminder4": "it's time to update snack calories!",
    "chooseReportType": "select report type",
    "oldWeight": "Recent weight",
    "bfpDesc": "Body Fat Percentage",
    "normalPerson": "Normal",
    "fatPerson": "Over",
    "obesePerson": "Obese",
    "nutTab": "Nutritions",
    "traceCode": "Tracking Code",
    "microNutrition": "Micronutrient",
    "targetStep": "Step goal",
    "foodIng": "You can customize this food easily",
    "howToDo": "Who to do:",
    "recommedation": "Recommend :",
    "veryLittleActivity": "Sedentary",
    "veryLittleActivity_description": "little or no exercise",
    "editorgangoal": "update",
    "InviteTextTitle": "Invite Friends",
    "newreminder": "Add reminder",
    "remindename": "Reminder name",
    "reminder5": "t's time to update water intake",
    "reminder6": "it's time to update your weight",
    "messagesubject": "Subject",
    "privacytitle": "The intimation of policy and privacy protection",
    "privacydesc": "Ø§Ø¹Ù„Ø§Ù…ÛŒÙ‡ Ø®Ø· Ù…Ø´ÛŒ Ùˆ Ø­ÙØ¸ Ø­Ø±ÛŒÙ… Ø®ØµÙˆØµÛŒ",
    "privacydes1": "Intimation of O2fit policy and privacy informs users about their responsibilities and makes them aware of selecting a behavior so that their personal information is not been abused.",
    "privacydes2": "This secrecy policy is complied and executed by international Oxygen data processing cooperation (Private Corporation), the owner of Oxygen software.",
    "privacydes3": "These policies may periodically amend or change. If there are made alternations based on collecting procedure, using, and or data transition, we make you aware of the reformed version of the secrecy policy through application and website. If you use the O2fit system after 4 days, it will be considered as awareness and acceptance of all the provisions. If O2fit starts to collect the information except for the mentioned cases in this intimation, it is obligatory to have your consent.",
    "privacydes4": "This intimation refers to the following cases:",
    "privacydestitle1": "1.A personal information set",
    "privacydestitle1des": "O2Fit collects and uses your information for Increase product quality and efficiency in websites and the other programs of Oxygen.\nO2fit will never share your information with others. If O2fit use them to develop its own business, it should present a behavior so that the users are not known.\n\nUsersâ€™ information\nFurthermore the information of an individual that is required to develop a user account, we also collect O2fit standard information, such as:\na) The information related to a personal diet as birth, height and weight, genes, and the special details of foods and drinks that you use and the exercises you do and your sent tests results.\nb) Email address or cellphone number\nc) Your IP address, browser type and, working operating system.\nd)  Visited and referred pages, websites, and visits dates and time.\ne) You make data available using the tools that exist on websites or through a program or send them publicly.  \nf) You may give the information to a user in a userâ€™s messages.\ng) The collected information from ads and third party firms.\nh) The information shared by tutors, and physicians. Also the information such as name, the firmâ€™s name and the pictures they have presented.\ni) Supplementary information: your information may be completed with the additional information of the other resources, such as the available public\nresources.",
    "privacydestitle2": "2. Using the personal information",
    "privacydestitle2des": "We will treat confidentially with the collected information, and we do not share your identification of personal information without your assenting.\nWe may:\n-Share the information that does not potentially cause your identification,like the average of users weight reduction and or general information about eating habits, diets, and exercises. And this information develops based on collected statics from data, and or data that does not determine as a special user.\n- For proving the services and products that you request us.\n- Whereas cooperating in challenges, competence, and opinion polls of O2fit, we may fulfill the advertisement with the other cooperated supporters.\n- To share the usersâ€™ unidentifiable information in events and market analysis for the commercial objectives for marketing or improving the services.\n- If, based on a legal judgment, O2fit is to be liable to give personal information to cognizable authorities.\nUsersâ€™ information is considered as a part of the international Oxygen data processing cooperation (Private Corporation) assets. So if there is done a commercial transaction, like integration with another firm, or purchasing a part of the international Oxygen data processing cooperation (Private Corporation) asset the considered organization is obliged to treat with usersâ€™ personal information, diets, and such information, according to the secrecy policy.\nIn some situations, we may take action through third party contractors to perform the services. In this way, they will be provided only with the necessary information to render the services (e.g. in the case of recovering a physical product to you by a contractor, your name and address are presented o the contractor) and all contractors are asked to endeavor in retaining the personal information.\nDespite all the above issues, usersâ€™ collected data, except ads in importing health to prove safety and health, and or the other Oxygen team software will not be used.",
    "privacydestitle3": "3. Collected information security",
    "privacydestitle3des": "We have done commercial-security measures to protect your information against security violations. For instance, we store the personal dietary information in a limited and safe accessible possibility. And we take advantage of standard firewalls and security software which have designed to protect the security and the information integrity.\nHowever, there is no guarantee for accessing information, revelation, alteration, or destruction of information.\nUsing O2fit and programs and websites and its services, you confirm the achieving the perception of these dangers and if each of the above cases occurs, we do not accuse the international Oxygen data processing cooperation (Private Corporation).",
    "privacydestitle4": "4. Supporting children privacy",
    "privacydestitle4des": "O2fitt.com is a popular site and we do not intend to serve the children. If you are less than 18 years old, you are not allowed to use a website, and or software of O2fit (see the public regulations of data protection (COPPA). The international Oxygen data processing cooperation (Private Corporation) will block such individualsâ€™ accounts.",
    "privacydestitle5": "5. Using cookies and tracking technology",
    "privacydestitle5des": "The cookies have short textual files that place on a userâ€™s hardware hard disc and make the access of primary information more simply as some regulations in reentering to a website, avoiding re-registration in any entrance to the website.\nWe use cookies to obtain internet usage knowledge improving content and advertisement, collecting visited sites data and in some cases, they are used to present the professional issues.\nSome of our advertisers and business partners sometimes use it. O2fit has no monitoring of used cookies by its advertisers and business partners.\nIf you donâ€™t want to use the cookies, you can achieve this wish by inactivating them on your browser. It is necessary to note that in this way, a part of the website may not act correctly.",
    "privacydestitle6": "6. Connecting with the other websites",
    "privacydestitle6des": "Our website may connect with other websites. Note that we arenâ€™t responsible for other websâ€™ and firmsâ€™ procedures for privacy protection. So we encourage you to investigate the other websitesâ€™ privacy protection policies that you connect to them in this way. The third partiesâ€™ proceedings and policies are not under our control.",
    "privacydestitle7": "7. Legal and civil bases",
    "privacydestitle7des": "For data processing, we will proceed based on the following bases:\nContrast revenue: if you begin to promote the program through the website, you must assist the necessities of O2fitâ€™s intended individualsâ€™ particulars presentation so that your request is agreed upon.\nSatisfaction: we are allowed by ourselves using some of your given personal information that has mentioned in this intimation of privacy protection policy, and we make you pleased.\nLegitimate advantage: Using your personal information to improve the products and services for commercial or health aims and the other Oxygen team software that would have done along with this policy are a part of our legitimate advantages has been proven by your satisfaction.\n Data processing: Usersâ€™ data processing toward their geographic condition and, based on local limitations, traffic and so on, will be performed according to the technical groupâ€™s decision making of the international Oxygen data processing cooperation (a private corporation), regarding Oxygen teamâ€™s defined algorithms.",
    "privacydestitle8": "8. Data preservation and information omission",
    "privacydestitle8des": "We will retain your personal information only until achieving the aims to which they have been gathered and processed, such as legitimate, regulatory, audit, and declarative accountability.\nOur policy is to retain your personal information for six months after your user account omission or disuse. It is necessary to note that the international Oxygen data processing cooperation (Private Corporation) secures the right of using usersâ€™ personal information along with this policy intimation for more than six months for itself. \nWhile say welcome to you, if there are any questions or suggestions, you can contact info@o2Fitt.com.",
    "privacydestitle9": "Oxygen Team",
    "privacydestitle9des": "The last update, On 21Jun. 2020",
    "incorrectcodealert": "The code entered is incorrect",
    "lowCalerieDanger": "According to the goal set by you, your daily calories budget is less than a 1200, we recommend you change your goal.\nDo you wish to continue?",
    "lowCalerieDanger2": "According to the goal set by you, your health is at risk\nPlease change your weekly goal",
    "lowCalerieDanger3": "According to the goal set by you, your calories budget is less than a 1200.\nIt is advised that you continue your diet under a physician's supervision.",
    "goalarivetime": "Reach the goal",
    "signupalert": "Please fill all fields",
    "addpersonalworkout": "Calorie",
    "msgCat1": "Financial",
    "msgCat2": "Management",
    "msgCat3": "Feedback/Suggest",
    "msgCat4": "Support",
    "budget": "Budget",
    "stepBurnedCal": "Burned",
    "dailyActivityControl": "Setting a Goal and Food Diary",
    "perweek": "gr/week",
    "caloriecardfood": "Food",
    "signupfillalert1": "Enter username",
    "signupfillalert2": "Enter username",
    "water": "Water",
    "movement": "Workouts",
    "addpersonalworkout": "Create Exercise",
    "toman": "Toman",
    "euro": "Eur",
    "shanbe": "Sat",
    "1shanbe": "Sun",
    "2shanbe": "Mon",
    "3shanbe": "Tue",
    "4shanbe": "Wed",
    "5shanbe": "Thu",
    "jome": "Fri",
    "searchyourfoodtitle": "Track an item to get started",
    "writeYourFood2": "Find supermarket food by scanning barcode ,easily",
    "plusExercise": "Exercise",
    "waterDailyBudget": "Budget",
    "numberOfSteps": "Enter your steps",
    "ingredientSearchHint": "Food search",
    "golInperWeek": "Weekly goal",
    "mainGoal": "Main goal",
    "noMatchedExercise": "Sorry,no matching exercises are available",
    "pesonalexercise": "Create Exercise",
    "nomatchpassandconfirmpass": "The passwords you entered don't match",
    "setYourStepsdesc": "Today steps",
    "perWeight": "Recent",
    "required": "Required",
    "optional": "Optional",
    "personalCalorie": "Personal calories",
    "addAteFoodTitle": "Track food",
    "confcodealert": "The code is incorrect\nTry again",
    "shapeBodybot": "Body analyze",
    "loginOrSignup": "Got a O2Fit account?",
    "references": "References",
    "deleteMessage": "Are you sure you want to delete the selected item?",
    "from": "/",
    "mealAnalyz": "Meal analysis",
    "mealNutrient": "The amount of calories and macronutrients",
    "overCalorie": "You use too much calorie",
    "editOrDeleteSleep": "Hold down the desired day to edit or delete the recorded sleep",
    "duplicatedFoodName": "The name of the food is duplicate",
    "calorieGive": "calories",
    "calorieRemain": "Remain",
    'productName': "Product name",
    "barcode": "Barcode serial",
    "enterNameProduct": "enter product name",
    "addProduct": "Add product",
    "send": "send",
    "cancel": "cancel",
    "lostBarcode": "Sorry, the desired food barcode was not found",
    "sendInfo": "Please send to Us food information thanks",
    "example": "exp:lay's classic chips",
    "thanksForSend": "thank you",
    "thanksForFeedBack": "thanks for your feedback",
    "emptyCreateFood": "You did'nt make food",
    "minerals": "minerals",
    "vitamins": "vitamins",
    "fats": "fats",
    "other": "other",
    "iron": "iron",
    "weightKg": "weight (Kg)",
    "heightCm": "height (cm)",
    "wristCm": "wrist (cm)",
    "weightLossRate": "Weight loss rate",
    "weightGainRate": "Weight gain rate",
    "sliderWeightSuggest": "Suggested weight range for you",
    "wrongPersonalDetails": "You did not enter your personal details correctly",
    "emailExample": "exp: yourmail@gmail.com",
    "phoneExample": "exp: 0912345678",
    "GoToLogin": "Login",
    "apdf": "Raw vegetables and fruits,Whole grains,Beef,Low fat yogurt,Seaweed",
    "aphf": "Caffeinated beverages,Refined carbohydrates,High sugar fruits,High-fat and ready meals",
    "apsd": "Diabetes, stroke,IBS and digestive problems,Constipation and water retention in the body",
    "apss": "Aerobic, HIIT,Walking, jogging, Jumping rope, Zumba,Swimming",
    "APAccumulationFats": "Accumulation of fat around the abdomen and chest",
    "APSlimmingSpeed": "Moderate (it is recommended to control your blood sugar levels)",
    "APCommonTendencies": "Starchy or sugary foods, diet drinks and caffeine",
    "APImproperDietResult": "Lack of energy and craving for starchy or sugary foods in the morning and after lunch",


    "thgdf": "Complex carbohydrates, low-fat dairy, fresh vegetables and fruits",
    "thghf": "Coconut oil, cheese, butter, canola oil, vegetable oils and seed oils, heavy meats, salty snacks, caffeinated beverages",
    "thgsd": "Heart and joint inflammation",
    "thgss": "walking, jogging, swimming, treadmill, elliptical trainer.",
    "THGAccumulationFats": "More fat builds up in the arms and chest, and less in the thighs and ankles",
    "THGSlimmingSpeed": "Moderate",
    "THGCommonTendencies": "Salty, fatty and ready meals",
    "THGImproperDietResult": "Start the day with good energy, in the evening without energy and craving salty and fatty and ready foods",



    "pedf": "Fiber-rich vegetables and fruits, small amounts of animal protein, non-dairy fats such as coconut oil, flaxseed, legumes and eggs",
    "pehf": "High-fat cheeses, cream, sauces, caffeine and alcohol, processed meats such as sausages, etc.",
    "pesd": "Diseases related to estrogen levels such as progesterone, inflammation of the joints, especially the thighs as cellulite, water retention, bloating",
    "pess": "running , step aerobics, dancing, Zumba, elliptical trainer",
    "PEAccumulationFats": "Accumulation of fat in the thighs and hips",
    "PESlimmingSpeed": "Slow",
    "PECommonTendencies": "High-fat dairy, high-calorie desserts, latte cafe",
    "PEImproperDietResult": "Unusual hunger between meals or late at night after dinner",



    "trdf": "Fiber-rich vegetables and fruits, small amounts of animal protein, non-dairy fats such as coconut oil, flaxseed, legumes and eggs",
    "trhf": "High-fat cheeses, cream, sauces, caffeine and alcohol, processed meats such as sausages, etc.",
    "trsd": "Diseases related to estrogen levels such as progesterone, inflammation of the joints, especially the thighs as cellulite, water retention, bloating",
    "trss": "running , step aerobics, dancing, Zumba, elliptical trainer",
    "TRAccumulationFats": "Accumulation of fat in the thighs and hips and Ankle",
    "TRSlimmingSpeed": "Slow",
    "TRCommonTendencies": "High-fat dairy, high-calorie desserts, latte cafe",
    "TRImproperDietResult": "Unusual hunger between meals or late at night after dinner",


    "rtrdf": "Complex carbohydrates, low-fat dairy, fresh vegetables and fruits",
    "rtrhf": "Coconut oil, cheese, butter, canola oil, vegetable oils and seed oils, heavy meats, salty snacks, caffeinated beverages",
    "rtrsd": "Heart disease",
    "rtrss": "Push-ups , Bench presses , Abdominal crunches, Reverse crunches",
    "RTRAccumulationFats": "Accumulation of fat in the arms and chest",
    "RTRSlimmingSpeed": "Moderate",
    "RTRCommonTendencies": "Salty, fatty and ready meals",
    "RTRImproperDietResult": "Start the day with good energy, in the evening without energy and craving salty and fatty and ready foods",



    "rcdf": "Balanced foods with carbohydrates, fats, proteins and fiber",
    "rchf": "Protein powder, shake, large chunks of meat",
    "rcsd": " vitamin deficiency",
    "rcss": "Planks, Push-ups , Pull-ups , walking , jogging , dance",
    "RCAccumulationFats": "Scatter",
    "RCSlimmingSpeed": "Fast",
    "RCCommonTendencies": "Eat food after satiety",
    "RCImproperDietResult": "Suffering from a variety of diseases",
    "breakFastReminderTitle": "breakfast reminder",
    "lunchReminderTitle": "lunch reminder",
    "dinnerReminderTitle": "dinner reminder",
    "waterReminderTitle": "water reminder",
    "weightReminderTitle": "weight reminder",
    "snackReminderTitle": "snack reminder",
    "dailyFoodMealAnalyz": "meals detail",
    "harmfulFoods": "Harmful foods",
    "AccumulationFats": "Fat accumulation",
    "SlimmingSpeed": "Weight loss speed",
    "CommonTendencies": "Tendencies",
    "ImproperDietResult": "The result of improper diet",
    "noReminderValue": "Please enter reminder name",
    "writeMessageTruely": "Please enter message",
    "bills": "bills",
    "enyItem": "no item found",
    "day": "day",
    "month": "month",
    "year": "year",
    "zigzag": "The daily calorie goal is calculated in a zigzag pattern, which means that you can get more calories on the weekend than on any other day.",
    "hardshipLevel": "hardship level:",
    "dataConfirmationHeader": "Are you sure about the information",
    "soHard": "so hard",
    "hard": "hard",
    "medium": "medium",
    "easy": "easy",
    "dailyTargetStep": "The goal of the daily walk",
    "stepTip": "Try to walk at least 7,000 steps a day",
    "calculatedCalorie": " * step for you * burns calories",
    "stepCounter": "Pedometer",
    "o2fitISCountingSteps": "O2Fit is counting steps",
    "o2fitisCountingStepsNum": "O2Fit is counting steps. Number of steps today",
    "on": "On",
    "off": "Off",
    "burnedCalorie": "burned",
    "calorieCountingGoal": "Goal",
    "wateCounter": "water",
    "dailyTarget": "target",
    "forceUpdateBtn": "Update",
    "expiredPremium": "Premium has expired",
    "expirePremiumDes": 'yearly premium with special discount',
    "reNew": "Renew",

    "PayCalorieName": "Calorie Counting",
    "PayCalorieTitle": "Accurate calorie counting",
    "PayCalorieSd": "Record foods and snacks, calculate it with O2Fit",
    "PayCalorieLd": "O2Fit has a large database of international and local foods along with various sports and activities.\nAll you have to do is record the foods you crave at different meals or the activities and sports you do, then you will see O2Fit calories burned.\nCalculate your calorie intake, macronutrients and micronutrients.\nO2Fit Calculates macronutrients and micronutrients based on your body type and Body shape.",
    "PayDietName": "Diet Plan",
    "PayDietTitle": "Diet Plan",
    "PayDietSd": "A healthy and specific diet is very important for fitness",
    "PayDietLd": "If you do not want to count calories and you decide to reach your goal with a healthy diet plan, O2Fit has made this possible for you and also has more than 20 different types of food as a substitute for you in each meal, than if from the meal. If you are not satisfied with the offer, it is possible to replace it with alternative foods. \ NWith the possibility of a daily diet, you no longer need to worry about calculating the daily intake of micronutrients and macronutrients.",
    "PayStepName": "Pedometer",
    "PayStepTitle": "Pedometer",
    "PayStepSd": "Control and manage calorie burning",
    "PayStepLd": "One of the most influential factors in weight changes is walking and the calories it burns in the path of weight change.\nYou can record the steps you take during the day and calculate the O2Fit according to your body characteristics by burning calories by walking.",
    "PayWaterName": "Water Tracker",
    "PayWaterTitle": "Water Tracker",
    "PayWaterSd": "Track your consumption water easily!",
    "PayWaterLd": "O2Fit determines the amount of water you should drink daily and, in addition to the water you drink, calculates the amount of water you absorb from food and automatically reduces the daily target.",
    "PayFoodMakerName": "Personal Recipe",
    "PayFoodMakerTitle": "Personal Recipe",
    "PayFoodMakerSd": "Make your own food and see how many calories and nutrients it has",
    "PayFoodMakerLd": "A unique feature of O2Fit is the food processor, write the name of the food, add the ingredients, choose the photo, the cooking method and the cooking time.Then state how much you consumed.\nNow you can see how much calories, water and nutrients you absorb through the food you make and then eat.\nWith this possibility, you will no longer lose calories and nutritional value of any food.",
    "PayMacName": "Track Macros",
    "PayMacTitle": "Track Macros & Micos",
    "PayMacSd": "Control the amount of daily nutritional value you receive",
    "PayMacLd": "In order to achieve scientific and principled fitness, just counting calories is not enough and you must be aware of the amount of fat, carbohydrates, proteins and vitamins that you receive daily from foods. You will find out what you get more or less in a day",
    "PaySleepName": "Sleep management",
    "PaySleepitle": "Sleep management",
    "PaySleepSd": "Control your daily sleep time",
    "PaySleepLd": "You can record the amount of time you spend on the day and see the monthly and weekly status report, average sleep duration, calorie intake and sleep rating",
    "PayMicName": "Micronutrients",
    "PayMictitle": "Track Macros & Micos",
    "PayMicSd": "Control the amount of daily nutritional value you receive",
    "PayMicLd": "In order to achieve scientific and principled fitness, just counting calories is not enough and you must be aware of the amount of fat, carbohydrates, proteins and vitamins that you receive daily from foods. You will find out what you get more or less in a day",
    "PayBAName": "Body analysis",
    "PayBAtitle": "Body analysis",
    "PayBASd": "Get to know your body better",
    "PayBALd": "Knowing your body and what condition it is in terms of fitness is very important and helps your fitness path.\nDetermines the daily nutrition. It even zigzags your daily calories, and your daily macronutrient and micronutrient goals are calculated based on your body type.",
    "PayDAName": "Daily analysis",
    "PayDAtitle": "Daily analysis",
    "PayDASd": "Always be aware of the nutritional value of your daily intake",
    "PayDALd": "Calorie counting alone is not enough to achieve scientific and basic fitness, and you must be aware of the amount of fat, carbohydrates, proteins and vitamins that you receive daily from foods.\nO2Fit calculates the target and the amount of nutritional value you receive daily, and you realize what you are getting more or less per day.",
    "PayMealAName": "Meal Analysis",
    "PayMealAtitle": "Meal Analysis",
    "PayMealSd": "Always be aware of the nutritional value received at each meal",
    "PayMealLd": "Calorie counting alone is not enough to achieve scientific and basic fitness, and you must be aware of the amount of fat, carbohydrates, proteins and vitamins that you receive daily from foods.\nO2Fit calculates the target and the amount of nutritional value you receive daily, and you realize what you are getting more or less per day.",
    "PayGoalName": "Goal change",
    "PayGoalAtitle": "Goal change",
    "PayGoalSd": "To achieve the desired weight must be planned",
    "PayGoalLd": "You can set two types of goals: Calorie goal and diet plan goal. You can go on your fitness path without any side effects and reach your desired weight.\n\nYou can also set goals for your steps and all micronutrients.",
    "PayNutGoalName": "Set a nutritional value goal",
    "PayNutGoalAtitle": "Set a nutritional value goal",
    "PayNutGoalSd": "The pulse of your health in your hands!",
    "PayNutGoalLd": "One of the conditions for achieving basic fitness is that you know how much your body needs each vitamin or macronutrient daily ?!\nO2Fit calculates these amounts of Rover according to your body's specifications, and you become aware of your body's daily needs, and you can receive the same amount of nutritional value.\nWith this possibility, everything is under your control!\nYou can also set goals for steps and all micronutrients",
    "PayFoodEditName": "Edit foods",
    "PayFoodEdittitle": "Edit foods",
    "PayFoodEditSd": "Edit foods according to what you eat",
    "PayFoodEditLd": "In O2Fit, the nutritional value of foods is calculated based on food ingredients, type of cooking and cooking time, and this is the most scientific and basic method of calorie counting and macro counting.\n\nIt is possible that you are food ingredients Change it according to your taste and see and record the complete calories and nutritional value of the same food and it will be stored forever so that you can use it later.",
    "PayBodyBName": "Cardio and strength videos",
    "PayBodyBtitle": "Exercises, Cardio and strength",
    "PayBodyBSd": "Exercise alongside the goal of calorie counting or diet",
    "PayBodyBLd": "The best fitness route is the one where in addition to counting calories or following a sports diet plan.\n\nO2Fit for you sports activities, cardio and bodybuilding along with video, recommendations, how to do and the amount of calories burned Provided.",
    "PayACalName": "Exercise calories",
    "PayACaltitle": "Exercise calories",
    "PayACalSd": "Exercise alongside the goal of calorie counting or diet",
    "PayACalLd": "The best fitness route is the one where in addition to counting calories or following a sports diet plan.\n\nO2Fit for you sports activities, cardio and bodybuilding along with video, recommendations, how to do and the amount of calories burned Provided.",
    "PayRecipeName": "Recipes",
    "PayRecipetitle": "Delicious recipes",
    "PayRecipeSd": "Quick, easy and healthy recipes",
    "PayRecipeLd": "Having a healthy and diverse recipe helps you weight loss or gain weight evenly.\nGain new experiences. And enjoy the taste of healthy and delicious food.",
    "PayReporteName": "Reports",
    "PayReporttitle": "Reports",
    "PayReportSd": "See the result of all your efforts",
    "PayReportLd": "If you do not know how you are doing in a given period of time and how you are moving towards the goal, it can help you a lot in your success in this direction. And ... you can report at different time intervals",
    "blogTitle": "Tap here to read useful information related to fitness, nutrition, exercise & more.",
    "getYourGoal": "Set a goal for everything",
    "getYourGoalTitle": "If you have a premium, you can see how much macronutrients and micronutrients your body needs, and you can also set goals for your weight and limbs to achieve your fitness goal faster and smarter.",
    "clickForAnalyse": "Tap here to analyze and be aware of your body condition",
    "plsInsertCarefuly": "For better body analysis, please enter the correct measurement",
    "weightchangechart": "Weight changes",
    "fillPassword": "Enter your password",
    "fillUserName": "Enter your username",
    "to": "up to",
    "askForReferralCode": "I have refferal code",
    "doesNotExist": "Incorrect email or password combination, please try again or register for free",
    "fitWeight": "Fit weight",
    "targetCalorieForDay": "Daily calorie",
    "vipdes1": 'Calorie counting, editing foods and making personal food',
    "vipdes2": "More than 1000 different recipes with nutritional value",
    "vipdes3": 'Daily analysis and permanent body analysis',
    "vipdes4": 'Access to all cardio and bodybuilding exercises',
    "vipdes5": "View reports and statistics from the target route",
    "whatisBodyA": "What is o2fit body analysis?",
    "whatIsBodyAdes": "O2Fit pays attention to everything!\nKnowing your body and what condition it is in terms of fitness is very important and helps your fitness path.\nBy entering the size of body, it analyzes the O2FIt of your body scientifically.\nBy updating the weight and size of your body, we automatically re-analyzes your body.\nAfter analyzing the body, you will be given very important and useful information about your body, and even the amount of fat, carbohydrates and protein that you should receive daily, is calculated based on your body physique.",
    "essentialFat": "Essential Fat",
    "athletes": "Athletics",
    "fitness": "Fitness",
    "acceptable": "Acceptable",
    "obese": "Obese",
    "fatClassifiation": "Body Fat Classifiation",
    "dietPlusCalorie": "Diet & Calorie counting",
    "calorieCounting": "Calorie Counting",
    "premiumAc": "Premium",
    "freeAc": "Free",
    "fillSteps": "Enter your steps",
    "save": "save",
    "yourAccountToDate1": "days left to premium",
    "addImage": "please add at least one image",
    "productMainImage": "product image",
    "nutritionalValueImage": "nutritions image",
    "wrongUserName": "UserName not found",
    "fiber": "fiber",
    "starRatingHeader": "Do you like O2Fit ?",
    "starRatingShortDes": "Rate us by selecting the number of stars",
    "starRatingLongDes": "We strive, for a better experience, comfort and health promotion. Your rating and opinion important for us. ",
    "notNow": "Not now",
    "sendFeedBack": "Submit",
    "emptyStars": "Choose one of the stars 1 to 5",
    "close": "close",
    "stepsDes":"Pedometer",
    "changeTimeSetting":"Adjust date",
    "timeZoneHeader":"Update your time zone",
    "timeZoneDes":"The time and date of your phone is behind or ahead of the current time. Please click on the link below to go to the settings section of your phone and set the calendar and clock to automatic mode.",
    "HGCommonTendencies": "Dairy and sugary carbohydrates",
    "HGSlimmingSpeed":"Fast, best metabolism, strong bones",
    "HGAccumulationFats":"Accumulation of fat in the arms, chest, knees and ankles",
    "fullAnalys": "Full analysis",
    "baseAnalys": "Base analysis",
    "fatAnalys": "Fat analysis",
    "weightAnalyze": "Weight analysis",
    "appliedInformation": "Applied information",
    "enterEmail":"Please enter you'r email address",
    "enterPhone":"Please enter you'r phone number",
    "dontHave":"dont have",
    "check":"Check",
    "have":"have one",
    "editBodyShape":"Measurements",
    "manualStep":"Manual steps",
    "backgroundProcessText":"O2Fit needs to be allowed to run in the background for better pedometer performance",
    "accept":"Allow",
    "disagree":"Later",
    "setPhoneNumber":"login"
}